class_name InputActions
extends RefCounted
## Semantic input action names used across the project.
##
## Gameplay code must never test physical keys/buttons directly: it asks for an
## action defined here. The actual key/pad bindings live in the Godot Input Map
## (project.godot) and are generated by `tools/setup_input_map.gd`.
## Adding touch controls or remapping later only touches the Input Map.

const MOVE_FORWARD := &"move_forward"
const MOVE_BACKWARD := &"move_backward"
const MOVE_LEFT := &"move_left"
const MOVE_RIGHT := &"move_right"
const JUMP := &"jump"
const RUN := &"run"
const INTERACT := &"interact"

const CAMERA_LEFT := &"camera_left"
const CAMERA_RIGHT := &"camera_right"
const CAMERA_UP := &"camera_up"
const CAMERA_DOWN := &"camera_down"

const TOGGLE_MOUSE_CAPTURE := &"toggle_mouse_capture"
const DEBUG_TOGGLE_HUD := &"debug_toggle_hud"

## Every action this project expects to exist. Used by the setup/validation tools.
const ALL: Array[StringName] = [
	MOVE_FORWARD, MOVE_BACKWARD, MOVE_LEFT, MOVE_RIGHT,
	JUMP, RUN, INTERACT,
	CAMERA_LEFT, CAMERA_RIGHT, CAMERA_UP, CAMERA_DOWN,
	TOGGLE_MOUSE_CAPTURE, DEBUG_TOGGLE_HUD,
]
